# Use postgres/example user/password credentials
version: '3.9'

services:

  test-db:
    image: postgres:16.3-bullseye
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 256mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qazwsx
      POSTGRES_DB: db

    ports:
      - "5432:5432"
